spring.data.mongodb.host=${MONGODB_HOST}
spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.username=${MONGODB_USERNAME}
spring.data.mongodb.password=${MONGODB_PASSWORD}
security.jwt.token.secret=${JWT_SECRET}
security.jwt.token.expiration=${JWT_EXPIRATION}